### ISSUE TITLE
Certificate chain verification logic - validate peer and all presented CA

### ISSUE THREAD

**Issue by kjnilsson** [rabbitmq/rabbitmq-trust-store#35]
related to #34

**Comment by akhishukla** [comment]
May I know what is the plan and schedule to fix this issue. I am using version 3.6.9 and still facing this issue.

**Comment by michaelklishin** [comment]
@akhishukla this is a secondary concern for this plugin at the moment. "Traditional" (as in RFC 5280 and 6818) peer verification is provided by Erlang's TLS implementation. If you need it, you probably don't want this plugin as it changes certificate validation strategy to be something else, by design.

**Comment by akhishukla** [comment]
Thanks for update. I just want to reconfirm the issue for the setup that I have.

My client's certificate is ca-chain: 
leaf->inter1->inter2->rootca

My server added/trusted the rootca and intermediates(inter1, inter2) to make the whitelist.

I understand this issue occurs for the above scenario only when I send just the client's leaf certificate(leaf) to connect server and expecting server to validate "leaf" against its whitelist (rootca, inter, inter2 )

However, I can get this working with slight modification at server by adding just "rootca" to its whitelist and not having "inter1" and "inter2" at server. While connecting from client I must send client's leaf certificate(leaf) along with its intermediates (inter1 and inter2) to allow server successfully validate against its whitelist(with only rootca).

Is my understanding of issue correct? Do you see any issue with this workaround?

**Comment by michaelklishin** [comment]
This client currently only checks leaf certificates against a periodically updated set. This issue is about implementing chain verification the same way RFC 5280 and 6818 describe it against a periodically updated set of trusted CAs ("trust anchors"). The only difference with what Erlang TLS implementation already implements is how the set of trusted certificates is computed.

I believe your understanding is correct. If sending intermediate certificates with the client one works for you, I don't see any issues with but I'd ask myself why this plugin is worth using in your case. If the answer is something other than "it would simplify certificate management in our environment", possibly you don't need this plugin at all.

Please post your questions to rabbitmq-users, RabbitMQ's public mailing list

**Comment by akhishukla** [comment]
@michaelklishin I believe this issue doesn't just applies to rabbitmq_trust_store plugin. Since you questioned that in my case it is not required, I looked into plugin list and found it is not enabled at all. 
[  ] rabbitmq_trust_store              3.6.9
The one which is enabled  for certificate validation is:
[E*] rabbitmq_auth_mechanism_ssl       3.6.9

So I think the Erlang TLS implementation making the difference here as well and causing the issue which I described in previous post. Do you agree?
If yes, do we have a similar defect for rabbitmq_auth_mechanism_ssl ? or let me know if it requires a fresh defect

**Comment by michaelklishin** [comment]
@akhishukla I do not necessarily see it as a defect. `rabbitmq_auth_mechanism_ssl` relies on Erlang's TLS' implementation to perform validation as RabbitMQ does not implement TLS.

There are multiple configurable parameters such as verification depth (mentioned in RabbitMQ TLS docs). You can even provide a custom function (which this plugin does) that will apply any logic you want.

This is not a discussion venue. Please take your questions about TLS in Erlang to erlang-questions.
