### ISSUE TITLE
Trust store crashes

### ISSUE THREAD

**Issue by thomaslitton** [rabbitmq/rabbitmq-trust-store#63]
We are seeing problems in which the trust store provider crashes.  This prevents client from connecting (because their certs are no longer trusted).

We see this problem on rabbitmq 3.6.10 (running Erlang 19.3)

The stack trace is:
** Generic server trust_store terminating 
** Last message in was refresh
** When Server state == {state,[{rabbit_trust_store_file_provider,nostate}],
                               15000}
** Reason for termination == 
** {function_clause,
       [{rabbit_trust_store,terminate,
            [{{badmatch,false},
              [{rabbit_trust_store_file_provider,ensure_directory,1,
                   [{file,\"src/rabbit_trust_store_file_provider.erl\"},
                    {line,95}]},
               {rabbit_trust_store_file_provider,directory_path,2,
                   [{file,\"src/rabbit_trust_store_file_provider.erl\"},
                    {line,79}]},
               {rabbit_trust_store_file_provider,list_certs,1,
                   [{file,\"src/rabbit_trust_store_file_provider

We are running rabbitmq in kubernetes and mapping the white list directory from a host path.

**Comment by thomaslitton** [comment]
We are also seeing a similar error that causes the same problem:

** Generic server trust_store terminating 
** Last message in was refresh
** When Server state == {state,[{rabbit_trust_store_file_provider,nostate}],
                               15000}
** Reason for termination ==           
** {function_clause,    
       [{rabbit_trust_store,terminate,
            [{{badmatch,{error,enoent}},        
              [{rabbit_trust_store_file_provider,modification_time,1,
                   [{file,\"src/rabbit_trust_store_file_provider.erl\"},
                    {line,60}]},
               {rabbit_trust_store_file_provider,'-list_certs_0/1-fun-0-',2,
                   [{file,\"src/rabbit_trust_store_file_provider.erl\"},
                    {line,53}]},
               {lists,map,2,[{file,\"lists.erl\"},{line,1239}]},
               {lists,map,2,[{file,\"lists.erl\"},{line,1239}]},
               {rabbit_trust_store_file_provider,list_certs,1,
                   [{file,\"src/rabbit_trust_store_file_provider.erl\"},
                    {line,20}]},
               {rabbit_trust_store,refresh_provider_certs,3,
                   [{file,\"src/rabbit_trust_store.erl\"},{line,223}]},
               {rabbit_trust_store,'-refresh_certs/2-fun-0-',4,
                   [{file,\"src/rabbit_trust_store.erl\"},{line,212}]},
               {lists,foldl,3,[{file,\"lists.erl\"},{line,1263}]}]},
             {state,[{rabbit_trust_store_file_provider,nostate}],15000}],
            [{file,\"src/rabbit_trust_store.erl\"},{line,170}]},
        {gen_server,try_terminate,3,[{file,\"gen_server.erl\"},{line,629}]},
        {gen_server,terminate,7,[{file,\"gen_server.erl\"},{line,795}]},
        {proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,247}]}]}

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by lukebakken** [comment]
Here is the line of code that is causing the `badmatch` error:

https://github.com/rabbitmq/rabbitmq-trust-store/blob/master/src/rabbit_trust_store_file_provider.erl#L95

What is happening is that the value you have configured for `directory` exists, but is *not* an actual directory. Can you double check that `directory` is set to a directory path and not to a file?
